name: scidart_io
description: SciDart IO is file manipulation library compatible with SciDart. This library is part of SciDart project https://scidart.org/).
version: 0.0.1-dev.4
homepage: https://scidart.org/

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.4
  scidart: ^0.0.1-dev.8

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
