name: scidart_io
description: SciDart IO is file manipulation library compatible with SciDart. This library is part of SciDart project https://scidart.org/).
version: 0.0.2-dev.1
homepage: https://scidart.org/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  universal_io: ^2.0.4
  scidart: ^0.0.2-dev.5

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
